<?php

/**
 *------
 * BGA framework: © Gregory Isabelli <gisabelli@boardgamearena.com> & Emmanuel Colin <ecolin@boardgamearena.com>
 * Dobble implementation : © <Your name here> <Your email address here>
 * 
 * This code has been produced on the BGA studio platform for use on http://boardgamearena.com.
 * See http://en.boardgamearena.com/#!doc/Studio for more information.
 * -----
 *
 * material.inc.php
 *
 * Dobble game material description
 *
 * Here, you can describe the material of your game with PHP variables.
 *   
 * This file is loaded in your game logic class constructor, ie these variables
 * are available everywhere in your game logic code.
 *
 */


/*

Example:

$this->card_types = array(
    1 => array( "card_name" => ...,
                ...
              )
);


*/
$this->symbols = [
  "ANCHOR" => "00",
  "APPLE" => "01",
  "BABY_BOTTLE" => "02",
  "BIRD" => "03",
  "BOMB" => "04",
  "BULB" => "05",
  "CACTUS" => "06",
  "CAMPFIRE" => "07",
  "CANDLE" => "08",
  "CAR" => "09",
  "CARROT" => "10",
  "CAT" => "11",
  "CHEESE" => "12",
  "CLOCK" => "13",
  "CLOVER" => "14",
  "CLOWN" => "15",
  "DINOSAUR" => "16",
  "DOBBLE" => "17",
  "DOG" => "18",
  "DOLPHIN" => "19",
  "DRAGON" => "20",
  "DROP" => "21",
  "EXCLAMATION" => "22",
  "EYE" => "23",
  "FLOWER" => "24",
  "FORBIDDEN" => "25",
  "GHOST" => "26",
  "HAMMER" => "27",
  "HEART" => "28",
  "ICECUBE" => "29",
  "IGLOO" => "30",
  "INTERROGATION" => "31",
  "JUMPER" => "32",
  "KEY" => "33",
  "LADYBUG" => "34",
  "LIGHTNING" => "35",
  "MAN" => "36",
  "MAPPLE" => "37",
  "MOON" => "38",
  "MOUTH" => "39",
  "PADLOCK" => "40",
  "PENCIL" => "41",
  "SCISSORS" => "42",
  "SKULL" => "43",
  "SNOWFLAKE" => "44",
  "SNOWMAN" => "45",
  "SPIDER" => "46",
  "STAIN" => "47",
  "SUN" => "48",
  "SUNGLASSES" => "49",
  "TARGET" => "50",
  "TREBLE_KEY" => "51",
  "TREE" => "52",
  "TURTLE" => "53",
  "WEB" => "54",
  "YIN_YANG" => "55",
  "ZEBRA" => "56",
];

$this->cards_description = array(
  '00' => [
    'type' => '0011212330314155',
    'zones' => [
      $this->symbols["ANCHOR"] => [
        "left" => "11",
        "top" => "60",
        "rotation" => "42",
        "size" => "22",
        "polygon" => "11% 19%, 2% 81%, 98% 80%, 102% 18%",
      ],
      $this->symbols["CAT"] => [
        "left" => "17",
        "top" => "16",
        "rotation" => "128",
        "size" => "19",
      ],
      $this->symbols["DROP"] => [
        "left" => "39",
        "top" => "40",
        "rotation" => "-47",
        "size" => "38",
      ],
      $this->symbols["EYE"] => [
        "left" => "34",
        "top" => "0",
        "rotation" => "185",
        "size" => "34",
      ],
      $this->symbols["IGLOO"] => [
        "left" => "31",
        "top" => "68",
        "rotation" => "0",
        "size" => "34",
      ],
      $this->symbols["INTERROGATION"] => [
        "left" => "56",
        "top" => "14",
        "rotation" => "222",
        "size" => "37",
      ],
      $this->symbols["PENCIL"] => [
        "left" => "77",
        "top" => "44",
        "rotation" => "5",
        "size" => "21",
      ],
      $this->symbols["YIN_YANG"] => [
        "left" => "13",
        "top" => "36",
        "rotation" => "-20",
        "size" => "28",
      ],
    ],
  ],
  '01' => [
    'type' => '0410152022263147',
    'zones' => [
      $this->symbols["BOMB"] => [
        "left" => "20",
        "top" => "55",
        "rotation" => "42",
        "size" => "41",
      ],
      $this->symbols["CARROT"] => [
        "left" => "13",
        "top" => "6",
        "rotation" => "128",
        "size" => "35",
      ],
      $this->symbols["CLOWN"] => [
        "left" => "53",
        "top" => "67",
        "rotation" => "-47",
        "size" => "29",
      ],
      $this->symbols["DRAGON"] => [
        "left" => "2",
        "top" => "35",
        "rotation" => "185",
        "size" => "34",
      ],
      $this->symbols["EXCLAMATION"] => [
        "left" => "65",
        "top" => "43",
        "rotation" => "0",
        "size" => "28",
      ],
      $this->symbols["GHOST"] => [
        "left" => "34",
        "top" => "32",
        "rotation" => "222",
        "size" => "34",
      ],
      $this->symbols["INTERROGATION"] => [
        "left" => "63",
        "top" => "18",
        "rotation" => "5",
        "size" => "31",
      ],
      $this->symbols["STAIN"] => [
        "left" => "38",
        "top" => "2",
        "rotation" => "-20",
        "size" => "33",
      ],
    ],
  ],
  '02' => [
    'type' => '1214222941505253',
    'zones' => [
      $this->symbols["CHEESE"] => [
        "left" => "6",
        "top" => "14",
        "rotation" => "42",
        "size" => "32",
      ],
      $this->symbols["CLOVER"] => [
        "left" => "6",
        "top" => "41",
        "rotation" => "128",
        "size" => "35",
      ],
      $this->symbols["EXCLAMATION"] => [
        "left" => "33",
        "top" => "5",
        "rotation" => "-47",
        "size" => "32",
      ],
      $this->symbols["ICECUBE"] => [
        "left" => "29",
        "top" => "70",
        "rotation" => "185",
        "size" => "26",
      ],
      $this->symbols["PENCIL"] => [
        "left" => "56",
        "top" => "12",
        "rotation" => "0",
        "size" => "31",
      ],
      $this->symbols["TARGET"] => [
        "left" => "74",
        "top" => "37",
        "rotation" => "222",
        "size" => "21",
      ],
      $this->symbols["TREE"] => [
        "left" => "51",
        "top" => "52",
        "rotation" => "5",
        "size" => "36",
      ],
      $this->symbols["TURTLE"] => [
        "left" => "32",
        "top" => "27",
        "rotation" => "-20",
        "size" => "40",
      ],
    ],
  ],
  '03' => [
    'type' => '0715172432343841',
    'zones' => [
      $this->symbols["CAMPFIRE"] => [
        "left" => "20",
        "top" => "65",
        "rotation" => "42",
        "size" => "30",
      ],
      $this->symbols["CLOWN"] => [
        "left" => "38",
        "top" => "26",
        "rotation" => "128",
        "size" => "25",
      ],
      $this->symbols["DOBBLE"] => [
        "left" => "63",
        "top" => "23",
        "rotation" => "-47",
        "size" => "35",
      ],
      $this->symbols["FLOWER"] => [
        "left" => "7",
        "top" => "19",
        "rotation" => "185",
        "size" => "27",
      ],
      $this->symbols["JUMPER"] => [
        "left" => "51",
        "top" => "44",
        "rotation" => "0",
        "size" => "40",
      ],
      $this->symbols["LADYBUG"] => [
        "left" => "44",
        "top" => "72",
        "rotation" => "222",
        "size" => "25",
      ],
      $this->symbols["MOON"] => [
        "left" => "4",
        "top" => "38",
        "rotation" => "5",
        "size" => "40",
      ],
      $this->symbols["PENCIL"] => [
        "left" => "29",
        "top" => "0",
        "rotation" => "-20",
        "size" => "37",
      ],
    ],
  ],
  '04' => [
    'type' => '0015253545464950',
    'zones' => [
      $this->symbols["ANCHOR"] => [
        "left" => "32",
        "top" => "59",
        "rotation" => "42",
        "size" => "36",
      ],
      $this->symbols["CLOWN"] => [
        "left" => "27",
        "top" => "16",
        "rotation" => "128",
        "size" => "45",
      ],
      $this->symbols["FORBIDDEN"] => [
        "left" => "59",
        "top" => "50",
        "rotation" => "-47",
        "size" => "32",
      ],
      $this->symbols["LIGHTNING"] => [
        "left" => "13",
        "top" => "57",
        "rotation" => "185",
        "size" => "23",
      ],
      $this->symbols["SNOWMAN"] => [
        "left" => "14",
        "top" => "7",
        "rotation" => "0",
        "size" => "26",
      ],
      $this->symbols["SPIDER"] => [
        "left" => "1",
        "top" => "32",
        "rotation" => "222",
        "size" => "32",
      ],
      $this->symbols["SUNGLASSES"] => [
        "left" => "75",
        "top" => "31",
        "rotation" => "5",
        "size" => "25",
      ],
      $this->symbols["TARGET"] => [
        "left" => "63",
        "top" => "12",
        "rotation" => "-20",
        "size" => "25",
      ],
    ],
  ],
  '05' => [
    'type' => '1719202328333750',
    'zones' => [
      $this->symbols["DOBBLE"] => [
        "left" => "49",
        "top" => "6",
        "rotation" => "42",
        "size" => "29",
      ],
      $this->symbols["DOLPHIN"] => [
        "left" => "1",
        "top" => "39",
        "rotation" => "128",
        "size" => "32",
      ],
      $this->symbols["DRAGON"] => [
        "left" => "32",
        "top" => "72",
        "rotation" => "-47",
        "size" => "25",
      ],
      $this->symbols["EYE"] => [
        "left" => "10",
        "top" => "9",
        "rotation" => "185",
        "size" => "31",
      ],
      $this->symbols["HEART"] => [
        "left" => "59",
        "top" => "30",
        "rotation" => "0",
        "size" => "36",
      ],
      $this->symbols["KEY"] => [
        "left" => "61",
        "top" => "62",
        "rotation" => "222",
        "size" => "29",
      ],
      $this->symbols["MAPPLE"] => [
        "left" => "31",
        "top" => "43",
        "rotation" => "5",
        "size" => "32",
      ],
      $this->symbols["TARGET"] => [
        "left" => "33",
        "top" => "19",
        "rotation" => "-20",
        "size" => "26",
      ],
    ],
  ],
  '06' => [
    'type' => '0917273142495356',
    'zones' => [
      $this->symbols["CAR"] => [
        "left" => "74",
        "top" => "32",
        "rotation" => "42",
        "size" => "23",
      ],
      $this->symbols["DOBBLE"] => [
        "left" => "54",
        "top" => "7",
        "rotation" => "128",
        "size" => "25",
      ],
      $this->symbols["HAMMER"] => [
        "left" => "10",
        "top" => "58",
        "rotation" => "-47",
        "size" => "39",
      ],
      $this->symbols["INTERROGATION"] => [
        "left" => "22",
        "top" => "7",
        "rotation" => "185",
        "size" => "27",
      ],
      $this->symbols["SCISSORS"] => [
        "left" => "1",
        "top" => "26",
        "rotation" => "0",
        "size" => "45",
      ],
      $this->symbols["SUNGLASSES"] => [
        "left" => "38",
        "top" => "20",
        "rotation" => "222",
        "size" => "42",
      ],
      $this->symbols["TURTLE"] => [
        "left" => "48",
        "top" => "76",
        "rotation" => "5",
        "size" => "25",
      ],
      $this->symbols["ZEBRA"] => [
        "left" => "45",
        "top" => "57",
        "rotation" => "-20",
        "size" => "29",
      ],
    ],
  ],
  '07' => [
    'type' => '0307222836495455',
    'zones' => [
      $this->symbols["BIRD"] => [
        "left" => "32",
        "top" => "28",
        "rotation" => "42",
        "size" => "46",
      ],
      $this->symbols["CAMPFIRE"] => [
        "left" => "18",
        "top" => "62",
        "rotation" => "128",
        "size" => "33",
      ],
      $this->symbols["EXCLAMATION"] => [
        "left" => "36",
        "top" => "5",
        "rotation" => "-47",
        "size" => "30",
      ],
      $this->symbols["HEART"] => [
        "left" => "77",
        "top" => "44",
        "rotation" => "185",
        "size" => "20",
      ],
      $this->symbols["MAN"] => [
        "left" => "12",
        "top" => "10",
        "rotation" => "0",
        "size" => "26",
      ],
      $this->symbols["SUNGLASSES"] => [
        "left" => "59",
        "top" => "8",
        "rotation" => "222",
        "size" => "32",
      ],
      $this->symbols["WEB"] => [
        "left" => "54",
        "top" => "63",
        "rotation" => "5",
        "size" => "28",
      ],
      $this->symbols["YIN_YANG"] => [
        "left" => "4",
        "top" => "35",
        "rotation" => "-20",
        "size" => "34",
      ],
    ],
  ],
  '08' => [
    'type' => '0106091028354143',
    'zones' => [
      $this->symbols["APPLE"] => [
        "left" => "40",
        "top" => "74",
        "rotation" => "42",
        "size" => "22",
      ],
      $this->symbols["CACTUS"] => [
        "left" => "60",
        "top" => "54",
        "rotation" => "128",
        "size" => "35",
      ],
      $this->symbols["CAR"] => [
        "left" => "72",
        "top" => "29",
        "rotation" => "-47",
        "size" => "27",
      ],
      $this->symbols["CARROT"] => [
        "left" => "2",
        "top" => "40",
        "rotation" => "185",
        "size" => "34",
      ],
      $this->symbols["HEART"] => [
        "left" => "47",
        "top" => "14",
        "rotation" => "0",
        "size" => "32",
      ],
      $this->symbols["LIGHTNING"] => [
        "left" => "31",
        "top" => "48",
        "rotation" => "222",
        "size" => "36",
      ],
      $this->symbols["PENCIL"] => [
        "left" => "31",
        "top" => "33",
        "rotation" => "5",
        "size" => "27",
      ],
      $this->symbols["SKULL"] => [
        "left" => "5",
        "top" => "6",
        "rotation" => "-20",
        "size" => "45",
      ],
    ],
  ],
  '09' => [
    'type' => '0309111415183748',
    'zones' => [
      $this->symbols["BIRD"] => [
        "left" => "75",
        "top" => "39",
        "rotation" => "42",
        "size" => "21",
      ],
      $this->symbols["CAR"] => [
        "left" => "64",
        "top" => "13",
        "rotation" => "128",
        "size" => "28",
      ],
      $this->symbols["CAT"] => [
        "left" => "14",
        "top" => "12",
        "rotation" => "-47",
        "size" => "32",
      ],
      $this->symbols["CLOVER"] => [
        "left" => "27",
        "top" => "22",
        "rotation" => "185",
        "size" => "48",
      ],
      $this->symbols["CLOWN"] => [
        "left" => "41",
        "top" => "2",
        "rotation" => "0",
        "size" => "23",
      ],
      $this->symbols["DOG"] => [
        "left" => "61",
        "top" => "55",
        "rotation" => "222",
        "size" => "31",
      ],
      $this->symbols["MAPPLE"] => [
        "left" => "9",
        "top" => "49",
        "rotation" => "5",
        "size" => "26",
      ],
      $this->symbols["SUN"] => [
        "left" => "31",
        "top" => "65",
        "rotation" => "0",
        "size" => "32",
      ],
    ],
  ],
  '10' => [
    'type' => '0306212738404750',
    'zones' => [
      $this->symbols["BIRD"] => [
        "left" => "63",
        "top" => "13",
        "rotation" => "42",
        "size" => "27",
      ],
      $this->symbols["CACTUS"] => [
        "left" => "41",
        "top" => "22",
        "rotation" => "128",
        "size" => "52",
      ],
      $this->symbols["DROP"] => [
        "left" => "71",
        "top" => "63",
        "rotation" => "-47",
        "size" => "18",
      ],
      $this->symbols["HAMMER"] => [
        "left" => "8",
        "top" => "56",
        "rotation" => "185",
        "size" => "39",
      ],
      $this->symbols["MOON"] => [
        "left" => "4",
        "top" => "30",
        "rotation" => "0",
        "size" => "40",
      ],
      $this->symbols["PADLOCK"] => [
        "left" => "42",
        "top" => "68",
        "rotation" => "222",
        "size" => "30",
      ],
      $this->symbols["STAIN"] => [
        "left" => "17",
        "top" => "9",
        "rotation" => "5",
        "size" => "25",
      ],
      $this->symbols["TARGET"] => [
        "left" => "43",
        "top" => "3",
        "rotation" => "-20",
        "size" => "23",
      ],
    ],
  ],
  '11' => [
    'type' => '0612171826394655',
    'zones' => [
      $this->symbols["CACTUS"] => [
        "left" => "55",
        "top" => "10",
        "rotation" => "42",
        "size" => "25",
      ],
      $this->symbols["CHEESE"] => [
        "left" => "16",
        "top" => "2",
        "rotation" => "128",
        "size" => "39",
      ],
      $this->symbols["DOBBLE"] => [
        "left" => "31",
        "top" => "35",
        "rotation" => "-47",
        "size" => "32",
      ],
      $this->symbols["DOG"] => [
        "left" => "56",
        "top" => "28",
        "rotation" => "185",
        "size" => "41",
      ],
      $this->symbols["GHOST"] => [
        "left" => "51",
        "top" => "60",
        "rotation" => "0",
        "size" => "33",
      ],
      $this->symbols["MOUTH"] => [
        "left" => "33",
        "top" => "72",
        "rotation" => "222",
        "size" => "32",
      ],
      $this->symbols["SPIDER"] => [
        "left" => "3",
        "top" => "33",
        "rotation" => "5",
        "size" => "32",
      ],
      $this->symbols["YIN_YANG"] => [
        "left" => "13",
        "top" => "61",
        "rotation" => "0",
        "size" => "26",
      ],
    ],
  ],
  '12' => [
    'type' => '1018192124444952',
    'zones' => [
      $this->symbols["CARROT"] => [
        "left" => "3",
        "top" => "48",
        "rotation" => "42",
        "size" => "44",
      ],
      $this->symbols["DOG"] => [
        "left" => "64",
        "top" => "17",
        "rotation" => "128",
        "size" => "27",
      ],
      $this->symbols["DOLPHIN"] => [
        "left" => "8",
        "top" => "26",
        "rotation" => "-47",
        "size" => "22",
      ],
      $this->symbols["DROP"] => [
        "left" => "73",
        "top" => "48",
        "rotation" => "185",
        "size" => "25",
      ],
      $this->symbols["FLOWER"] => [
        "left" => "29",
        "top" => "6",
        "rotation" => "0",
        "size" => "22",
      ],
      $this->symbols["SNOWFLAKE"] => [
        "left" => "39",
        "top" => "79",
        "rotation" => "222",
        "size" => "19",
      ],
      $this->symbols["SUNGLASSES"] => [
        "left" => "29",
        "top" => "18",
        "rotation" => "5",
        "size" => "34",
      ],
      $this->symbols["TREE"] => [
        "left" => "41",
        "top" => "41",
        "rotation" => "-20",
        "size" => "43",
      ],
    ],
  ],
  '13' => [
    'type' => '1421262832424551',
    'zones' => [
      $this->symbols["CLOVER"] => [
        "left" => "13",
        "top" => "58",
        "rotation" => "42",
        "size" => "28",
      ],
      $this->symbols["DROP"] => [
        "left" => "62",
        "top" => "17",
        "rotation" => "128",
        "size" => "20",
      ],
      $this->symbols["GHOST"] => [
        "left" => "53",
        "top" => "24",
        "rotation" => "-47",
        "size" => "42",
      ],
      $this->symbols["HEART"] => [
        "left" => "37",
        "top" => "9",
        "rotation" => "185",
        "size" => "29",
      ],
      $this->symbols["JUMPER"] => [
        "left" => "58",
        "top" => "58",
        "rotation" => "0",
        "size" => "29",
      ],
      $this->symbols["SCISSORS"] => [
        "left" => "7",
        "top" => "31",
        "rotation" => "222",
        "size" => "34",
      ],
      $this->symbols["SNOWMAN"] => [
        "left" => "11",
        "top" => "10",
        "rotation" => "5",
        "size" => "30",
      ],
      $this->symbols["TREBLE_KEY"] => [
        "left" => "32",
        "top" => "45",
        "rotation" => "-20",
        "size" => "37",
      ],
    ],
  ],
  '14' => [
    'type' => '0913232526363852',
    'zones' => [
      $this->symbols["CAR"] => [
        "left" => "49",
        "top" => "36",
        "rotation" => "42",
        "size" => "27",
      ],
      $this->symbols["CLOCK"] => [
        "left" => "10",
        "top" => "55",
        "rotation" => "128",
        "size" => "27",
      ],
      $this->symbols["EYE"] => [
        "left" => "38",
        "top" => "1",
        "rotation" => "-47",
        "size" => "30",
      ],
      $this->symbols["FORBIDDEN"] => [
        "left" => "33",
        "top" => "66",
        "rotation" => "185",
        "size" => "30",
      ],
      $this->symbols["GHOST"] => [
        "left" => "56",
        "top" => "16",
        "rotation" => "0",
        "size" => "34",
      ],
      $this->symbols["MAN"] => [
        "left" => "16",
        "top" => "8",
        "rotation" => "222",
        "size" => "21",
      ],
      $this->symbols["MOON"] => [
        "left" => "13",
        "top" => "23",
        "rotation" => "5",
        "size" => "38",
      ],
      $this->symbols["TREE"] => [
        "left" => "61",
        "top" => "54",
        "rotation" => "-20",
        "size" => "29",
      ],
    ],
  ],
  '15' => [
    'type' => '0203313233434652',
    'zones' => [
      $this->symbols["BABY_BOTTLE"] => [
        "left" => "14",
        "top" => "61",
        "rotation" => "42",
        "size" => "28",
      ],
      $this->symbols["BIRD"] => [
        "left" => "50",
        "top" => "7",
        "rotation" => "128",
        "size" => "28",
      ],
      $this->symbols["INTERROGATION"] => [
        "left" => "25",
        "top" => "4",
        "rotation" => "-47",
        "size" => "27",
      ],
      $this->symbols["JUMPER"] => [
        "left" => "58",
        "top" => "57",
        "rotation" => "185",
        "size" => "32",
      ],
      $this->symbols["KEY"] => [
        "left" => "29",
        "top" => "68",
        "rotation" => "0",
        "size" => "38",
      ],
      $this->symbols["SKULL"] => [
        "left" => "23",
        "top" => "30",
        "rotation" => "222",
        "size" => "36",
      ],
      $this->symbols["SPIDER"] => [
        "left" => "5",
        "top" => "43",
        "rotation" => "5",
        "size" => "20",
      ],
      $this->symbols["TREE"] => [
        "left" => "56",
        "top" => "29",
        "rotation" => "-20",
        "size" => "39",
      ],
    ],
  ],
  '16' => [
    'type' => '0608111922253256',
    'zones' => [
      $this->symbols["CACTUS"] => [
        "left" => "62",
        "top" => "14",
        "rotation" => "42",
        "size" => "25",
      ],
      $this->symbols["CANDLE"] => [
        "left" => "32",
        "top" => "34",
        "rotation" => "128",
        "size" => "35",
      ],
      $this->symbols["CAT"] => [
        "left" => "11",
        "top" => "14",
        "rotation" => "-47",
        "size" => "41",
      ],
      $this->symbols["DOLPHIN"] => [
        "left" => "6",
        "top" => "49",
        "rotation" => "185",
        "size" => "32",
      ],
      $this->symbols["EXCLAMATION"] => [
        "left" => "39",
        "top" => "4",
        "rotation" => "0",
        "size" => "27",
      ],
      $this->symbols["FORBIDDEN"] => [
        "left" => "59",
        "top" => "60",
        "rotation" => "222",
        "size" => "27",
      ],
      $this->symbols["JUMPER"] => [
        "left" => "67",
        "top" => "35",
        "rotation" => "5",
        "size" => "30",
      ],
      $this->symbols["ZEBRA"] => [
        "left" => "28",
        "top" => "65",
        "rotation" => "-20",
        "size" => "36",
      ],
    ],
  ],
  '17' => [
    'type' => '1618253341424754',
    'zones' => [
      $this->symbols["DINOSAUR"] => [
        "left" => "7",
        "top" => "56",
        "rotation" => "42",
        "size" => "30",
      ],
      $this->symbols["DOG"] => [
        "left" => "40",
        "top" => "27",
        "rotation" => "128",
        "size" => "30",
      ],
      $this->symbols["FORBIDDEN"] => [
        "left" => "66",
        "top" => "19",
        "rotation" => "-47",
        "size" => "21",
      ],
      $this->symbols["KEY"] => [
        "left" => "63",
        "top" => "40",
        "rotation" => "185",
        "size" => "28",
      ],
      $this->symbols["PENCIL"] => [
        "left" => "42",
        "top" => "3",
        "rotation" => "0",
        "size" => "25",
      ],
      $this->symbols["SCISSORS"] => [
        "left" => "4",
        "top" => "27",
        "rotation" => "222",
        "size" => "39",
      ],
      $this->symbols["STAIN"] => [
        "left" => "18",
        "top" => "10",
        "rotation" => "5",
        "size" => "21",
      ],
      $this->symbols["WEB"] => [
        "left" => "29",
        "top" => "56",
        "rotation" => "-20",
        "size" => "39",
      ],
    ],
  ],
  '18' => [
    'type' => '0105121521333656',
    'zones' => [
      $this->symbols["APPLE"] => [
        "left" => "27",
        "top" => "69",
        "rotation" => "0",
        "size" => "26",
      ],
      $this->symbols["BULB"] => [
        "left" => "39",
        "top" => "36",
        "rotation" => "128",
        "size" => "33",
      ],
      $this->symbols["CHEESE"] => [
        "left" => "8",
        "top" => "13",
        "rotation" => "-47",
        "size" => "42",
      ],
      $this->symbols["CLOWN"] => [
        "left" => "43",
        "top" => "4",
        "rotation" => "185",
        "size" => "27",
      ],
      $this->symbols["DROP"] => [
        "left" => "61",
        "top" => "19",
        "rotation" => "0",
        "size" => "24",
      ],
      $this->symbols["KEY"] => [
        "left" => "69",
        "top" => "36",
        "rotation" => "222",
        "size" => "32",
      ],
      $this->symbols["MAN"] => [
        "left" => "5",
        "top" => "47",
        "rotation" => "5",
        "size" => "32",
      ],
      $this->symbols["ZEBRA"] => [
        "left" => "53",
        "top" => "62",
        "rotation" => "-20",
        "size" => "29",
      ],
    ],
  ],
  '19' => [
    'type' => '2426304348505456',
    'zones' => [
      $this->symbols["FLOWER"] => [
        "left" => "14",
        "top" => "13",
        "rotation" => "42",
        "size" => "22",
      ],
      $this->symbols["GHOST"] => [
        "left" => "60",
        "top" => "23",
        "rotation" => "128",
        "size" => "27",
      ],
      $this->symbols["IGLOO"] => [
        "left" => "16",
        "top" => "66",
        "rotation" => "-47",
        "size" => "27",
      ],
      $this->symbols["SKULL"] => [
        "left" => "3",
        "top" => "35",
        "rotation" => "185",
        "size" => "35",
      ],
      $this->symbols["SUN"] => [
        "left" => "39",
        "top" => "54",
        "rotation" => "0",
        "size" => "40",
      ],
      $this->symbols["TARGET"] => [
        "left" => "36",
        "top" => "2",
        "rotation" => "222",
        "size" => "30",
      ],
      $this->symbols["WEB"] => [
        "left" => "70",
        "top" => "45",
        "rotation" => "5",
        "size" => "26",
      ],
      $this->symbols["ZEBRA"] => [
        "left" => "33",
        "top" => "32",
        "rotation" => "-20",
        "size" => "27",
      ],
    ],
  ],
  '20' => [
    'type' => '0104111740455254',
    'zones' => [
      $this->symbols["APPLE"] => [
        "left" => "62",
        "top" => "39",
        "rotation" => "42",
        "size" => "26",
      ],
      $this->symbols["BOMB"] => [
        "left" => "26",
        "top" => "71",
        "rotation" => "128",
        "size" => "21",
      ],
      $this->symbols["CAT"] => [
        "left" => "10",
        "top" => "47",
        "rotation" => "-47",
        "size" => "29",
      ],
      $this->symbols["DOBBLE"] => [
        "left" => "22",
        "top" => "5",
        "rotation" => "185",
        "size" => "45",
      ],
      $this->symbols["PADLOCK"] => [
        "left" => "44",
        "top" => "57",
        "rotation" => "0",
        "size" => "43",
      ],
      $this->symbols["SNOWMAN"] => [
        "left" => "9",
        "top" => "26",
        "rotation" => "222",
        "size" => "27",
      ],
      $this->symbols["TREE"] => [
        "left" => "59",
        "top" => "13",
        "rotation" => "5",
        "size" => "29",
      ],
      $this->symbols["WEB"] => [
        "left" => "38",
        "top" => "50",
        "rotation" => "-20",
        "size" => "20",
      ],
    ],
  ],
  '21' => [
    'type' => '0123293239474849',
    'zones' => [
      $this->symbols["APPLE"] => [
        "left" => "47",
        "top" => "63",
        "rotation" => "42",
        "size" => "27",
      ],
      $this->symbols["EYE"] => [
        "left" => "35",
        "top" => "1",
        "rotation" => "128",
        "size" => "26",
      ],
      $this->symbols["ICECUBE"] => [
        "left" => "2",
        "top" => "26",
        "rotation" => "-47",
        "size" => "44",
      ],
      $this->symbols["JUMPER"] => [
        "left" => "65",
        "top" => "44",
        "rotation" => "185",
        "size" => "29",
      ],
      $this->symbols["MOUTH"] => [
        "left" => "25",
        "top" => "68",
        "rotation" => "0",
        "size" => "27",
      ],
      $this->symbols["STAIN"] => [
        "left" => "17",
        "top" => "12",
        "rotation" => "222",
        "size" => "17",
      ],
      $this->symbols["SUN"] => [
        "left" => "42",
        "top" => "28",
        "rotation" => "5",
        "size" => "28",
      ],
      $this->symbols["SUNGLASSES"] => [
        "left" => "57",
        "top" => "12",
        "rotation" => "-20",
        "size" => "36",
      ],
    ],
  ],
  '22' => [
    'type' => '1225283134404448',
    'zones' => [
      $this->symbols["CHEESE"] => [
        "left" => "11",
        "top" => "11",
        "rotation" => "42",
        "size" => "33",
      ],
      $this->symbols["FORBIDDEN"] => [
        "left" => "79",
        "top" => "45",
        "rotation" => "128",
        "size" => "18",
      ],
      $this->symbols["HEART"] => [
        "left" => "59",
        "top" => "18",
        "rotation" => "-47",
        "size" => "30",
      ],
      $this->symbols["INTERROGATION"] => [
        "left" => "41",
        "top" => "5",
        "rotation" => "185",
        "size" => "24",
      ],
      $this->symbols["LADYBUG"] => [
        "left" => "6",
        "top" => "47",
        "rotation" => "0",
        "size" => "30",
      ],
      $this->symbols["PADLOCK"] => [
        "left" => "26",
        "top" => "64",
        "rotation" => "222",
        "size" => "33",
      ],
      $this->symbols["SNOWFLAKE"] => [
        "left" => "31",
        "top" => "30",
        "rotation" => "5",
        "size" => "39",
      ],
      $this->symbols["SUN"] => [
        "left" => "62",
        "top" => "57",
        "rotation" => "-20",
        "size" => "27",
      ],
    ],
  ],
  '23' => [
    'type' => '0009222433394051',
    'zones' => [
      $this->symbols["ANCHOR"] => [
        "left" => "30",
        "top" => "41",
        "rotation" => "42",
        "size" => "28",
      ],
      $this->symbols["CAR"] => [
        "left" => "50",
        "top" => "8",
        "rotation" => "128",
        "size" => "41",
      ],
      $this->symbols["EXCLAMATION"] => [
        "left" => "30",
        "top" => "6",
        "rotation" => "-47",
        "size" => "23",
      ],
      $this->symbols["FLOWER"] => [
        "left" => "11",
        "top" => "21",
        "rotation" => "185",
        "size" => "25",
      ],
      $this->symbols["KEY"] => [
        "left" => "75",
        "top" => "50",
        "rotation" => "0",
        "size" => "23",
      ],
      $this->symbols["MOUTH"] => [
        "left" => "14",
        "top" => "55",
        "rotation" => "222",
        "size" => "52",
      ],
      $this->symbols["PADLOCK"] => [
        "left" => "52",
        "top" => "48",
        "rotation" => "5",
        "size" => "31",
      ],
      $this->symbols["TREBLE_KEY"] => [
        "left" => "5",
        "top" => "44",
        "rotation" => "-20",
        "size" => "27",
      ],
    ],
  ],
  '24' => [
    'type' => '0313203941444556',
    'zones' => [
      $this->symbols["BIRD"] => [
        "left" => "65",
        "top" => "18",
        "rotation" => "42",
        "size" => "26",
      ],
      $this->symbols["CLOCK"] => [
        "left" => "9",
        "top" => "18",
        "rotation" => "128",
        "size" => "31",
      ],
      $this->symbols["DRAGON"] => [
        "left" => "38",
        "top" => "31",
        "rotation" => "-47",
        "size" => "37",
      ],
      $this->symbols["MOUTH"] => [
        "left" => "59",
        "top" => "63",
        "rotation" => "185",
        "size" => "26",
      ],
      $this->symbols["PENCIL"] => [
        "left" => "41",
        "top" => "4",
        "rotation" => "0",
        "size" => "28",
      ],
      $this->symbols["SNOWFLAKE"] => [
        "left" => "34",
        "top" => "70",
        "rotation" => "222",
        "size" => "23",
      ],
      $this->symbols["SNOWMAN"] => [
        "left" => "7",
        "top" => "46",
        "rotation" => "5",
        "size" => "34",
      ],
      $this->symbols["ZEBRA"] => [
        "left" => "73",
        "top" => "41",
        "rotation" => "-20",
        "size" => "24",
      ],
    ],
  ],
  '25' => [
    'type' => '0206152344515354',
    'zones' => [
      $this->symbols["BABY_BOTTLE"] => [
        "left" => "4",
        "top" => "35",
        "rotation" => "42",
        "size" => "37",
      ],
      $this->symbols["CACTUS"] => [
        "left" => "68",
        "top" => "33",
        "rotation" => "128",
        "size" => "29",
      ],
      $this->symbols["CLOWN"] => [
        "left" => "66",
        "top" => "16",
        "rotation" => "-47",
        "size" => "21",
      ],
      $this->symbols["EYE"] => [
        "left" => "32",
        "top" => "-3",
        "rotation" => "185",
        "size" => "37",
      ],
      $this->symbols["SNOWFLAKE"] => [
        "left" => "31",
        "top" => "54",
        "rotation" => "0",
        "size" => "38",
      ],
      $this->symbols["TREBLE_KEY"] => [
        "left" => "70",
        "top" => "60",
        "rotation" => "222",
        "size" => "20",
      ],
      $this->symbols["TURTLE"] => [
        "left" => "8",
        "top" => "18",
        "rotation" => "5",
        "size" => "33",
      ],
      $this->symbols["WEB"] => [
        "left" => "40",
        "top" => "31",
        "rotation" => "-20",
        "size" => "24",
      ],
    ],
  ],
  '26' => [
    'type' => '0107081318315051',
    'zones' => [
      $this->symbols["APPLE"] => [
        "left" => "59",
        "top" => "50",
        "rotation" => "42",
        "size" => "32",
      ],
      $this->symbols["CAMPFIRE"] => [
        "left" => "15",
        "top" => "14",
        "rotation" => "128",
        "size" => "40",
      ],
      $this->symbols["CANDLE"] => [
        "left" => "19",
        "top" => "60",
        "rotation" => "-47",
        "size" => "30",
      ],
      $this->symbols["CLOCK"] => [
        "left" => "5",
        "top" => "44",
        "rotation" => "185",
        "size" => "29",
      ],
      $this->symbols["DOG"] => [
        "left" => "71",
        "top" => "30",
        "rotation" => "0",
        "size" => "22",
      ],
      $this->symbols["INTERROGATION"] => [
        "left" => "45",
        "top" => "4",
        "rotation" => "222",
        "size" => "25",
      ],
      $this->symbols["TARGET"] => [
        "left" => "55",
        "top" => "31",
        "rotation" => "5",
        "size" => "16",
      ],
      $this->symbols["TREBLE_KEY"] => [
        "left" => "38",
        "top" => "64",
        "rotation" => "-20",
        "size" => "31",
      ],
    ],
  ],
  '27' => [
    'type' => '0213161721223548',
    'zones' => [
      $this->symbols["BABY_BOTTLE"] => [
        "left" => "22",
        "top" => "62",
        "rotation" => "42",
        "size" => "17",
      ],
      $this->symbols["CLOCK"] => [
        "left" => "36",
        "top" => "60",
        "rotation" => "128",
        "size" => "33",
      ],
      $this->symbols["DINOSAUR"] => [
        "left" => "4",
        "top" => "44",
        "rotation" => "-47",
        "size" => "31",
      ],
      $this->symbols["DOBBLE"] => [
        "left" => "37",
        "top" => "35",
        "rotation" => "185",
        "size" => "26",
      ],
      $this->symbols["DROP"] => [
        "left" => "60",
        "top" => "16",
        "rotation" => "0",
        "size" => "33",
      ],
      $this->symbols["EXCLAMATION"] => [
        "left" => "37",
        "top" => "5",
        "rotation" => "222",
        "size" => "33",
      ],
      $this->symbols["LIGHTNING"] => [
        "left" => "15",
        "top" => "11",
        "rotation" => "5",
        "size" => "32",
      ],
      $this->symbols["SUN"] => [
        "left" => "63",
        "top" => "44",
        "rotation" => "-20",
        "size" => "29",
      ],
    ],
  ],
  '28' => [
    'type' => '0205082637404149',
    'zones' => [
      $this->symbols["BABY_BOTTLE"] => [
        "left" => "33",
        "top" => "63",
        "rotation" => "42",
        "size" => "34",
      ],
      $this->symbols["BULB"] => [
        "left" => "23",
        "top" => "38",
        "rotation" => "128",
        "size" => "33",
      ],
      $this->symbols["CANDLE"] => [
        "left" => "14",
        "top" => "60",
        "rotation" => "-47",
        "size" => "27",
      ],
      $this->symbols["GHOST"] => [
        "left" => "52",
        "top" => "42",
        "rotation" => "185",
        "size" => "41",
      ],
      $this->symbols["MAPPLE"] => [
        "left" => "10",
        "top" => "19",
        "rotation" => "0",
        "size" => "28",
      ],
      $this->symbols["PADLOCK"] => [
        "left" => "48",
        "top" => "25",
        "rotation" => "222",
        "size" => "29",
      ],
      $this->symbols["PENCIL"] => [
        "left" => "37",
        "top" => "3",
        "rotation" => "5",
        "size" => "29",
      ],
      $this->symbols["SUNGLASSES"] => [
        "left" => "65",
        "top" => "13",
        "rotation" => "-20",
        "size" => "27",
      ],
    ],
  ],
  '29' => [
    'type' => '0815162728303952',
    'zones' => [
      $this->symbols["CANDLE"] => [
        "left" => "39",
        "top" => "62",
        "rotation" => "42",
        "size" => "30",
      ],
      $this->symbols["CLOWN"] => [
        "left" => "44",
        "top" => "6",
        "rotation" => "128",
        "size" => "24",
      ],
      $this->symbols["DINOSAUR"] => [
        "left" => "6",
        "top" => "40",
        "rotation" => "-47",
        "size" => "52",
      ],
      $this->symbols["HAMMER"] => [
        "left" => "12",
        "top" => "6",
        "rotation" => "185",
        "size" => "36",
      ],
      $this->symbols["HEART"] => [
        "left" => "37",
        "top" => "29",
        "rotation" => "0",
        "size" => "22",
      ],
      $this->symbols["IGLOO"] => [
        "left" => "3",
        "top" => "40",
        "rotation" => "222",
        "size" => "27",
      ],
      $this->symbols["MOUTH"] => [
        "left" => "62",
        "top" => "57",
        "rotation" => "5",
        "size" => "28",
      ],
      $this->symbols["TREE"] => [
        "left" => "57",
        "top" => "27",
        "rotation" => "-20",
        "size" => "36",
      ],
    ],
  ],
  '30' => [
    'type' => '0405091632445055',
    'zones' => [
      $this->symbols["CHEESE"] => [
        "left" => "6",
        "top" => "14",
        "rotation" => "42",
        "size" => "32",
      ],
      $this->symbols["CLOVER"] => [
        "left" => "6",
        "top" => "41",
        "rotation" => "128",
        "size" => "35",
      ],
      $this->symbols["EXCLAMATION"] => [
        "left" => "33",
        "top" => "5",
        "rotation" => "-47",
        "size" => "32",
      ],
      $this->symbols["ICECUBE"] => [
        "left" => "29",
        "top" => "70",
        "rotation" => "185",
        "size" => "26",
      ],
      $this->symbols["PENCIL"] => [
        "left" => "56",
        "top" => "12",
        "rotation" => "0",
        "size" => "31",
      ],
      $this->symbols["TARGET"] => [
        "left" => "74",
        "top" => "37",
        "rotation" => "222",
        "size" => "21",
      ],
      $this->symbols["TREE"] => [
        "left" => "51",
        "top" => "52",
        "rotation" => "5",
        "size" => "36",
      ],
      $this->symbols["TURTLE"] => [
        "left" => "32",
        "top" => "27",
        "rotation" => "-20",
        "size" => "40",
      ],
    ],
  ],
  '31' => [
    'type' => '0305101725293051',
    'zones' => [
      $this->symbols["CHEESE"] => [
        "left" => "6",
        "top" => "14",
        "rotation" => "42",
        "size" => "32",
      ],
      $this->symbols["CLOVER"] => [
        "left" => "6",
        "top" => "41",
        "rotation" => "128",
        "size" => "35",
      ],
      $this->symbols["EXCLAMATION"] => [
        "left" => "33",
        "top" => "5",
        "rotation" => "-47",
        "size" => "32",
      ],
      $this->symbols["ICECUBE"] => [
        "left" => "29",
        "top" => "70",
        "rotation" => "185",
        "size" => "26",
      ],
      $this->symbols["PENCIL"] => [
        "left" => "56",
        "top" => "12",
        "rotation" => "0",
        "size" => "31",
      ],
      $this->symbols["TARGET"] => [
        "left" => "74",
        "top" => "37",
        "rotation" => "222",
        "size" => "21",
      ],
      $this->symbols["TREE"] => [
        "left" => "51",
        "top" => "52",
        "rotation" => "5",
        "size" => "36",
      ],
      $this->symbols["TURTLE"] => [
        "left" => "32",
        "top" => "27",
        "rotation" => "-20",
        "size" => "40",
      ],
    ],
  ],
  '32' => [
    'type' => '0406131430333449',
    'zones' => [
      $this->symbols["CHEESE"] => [
        "left" => "6",
        "top" => "14",
        "rotation" => "42",
        "size" => "32",
      ],
      $this->symbols["CLOVER"] => [
        "left" => "6",
        "top" => "41",
        "rotation" => "128",
        "size" => "35",
      ],
      $this->symbols["EXCLAMATION"] => [
        "left" => "33",
        "top" => "5",
        "rotation" => "-47",
        "size" => "32",
      ],
      $this->symbols["ICECUBE"] => [
        "left" => "29",
        "top" => "70",
        "rotation" => "185",
        "size" => "26",
      ],
      $this->symbols["PENCIL"] => [
        "left" => "56",
        "top" => "12",
        "rotation" => "0",
        "size" => "31",
      ],
      $this->symbols["TARGET"] => [
        "left" => "74",
        "top" => "37",
        "rotation" => "222",
        "size" => "21",
      ],
      $this->symbols["TREE"] => [
        "left" => "51",
        "top" => "52",
        "rotation" => "5",
        "size" => "36",
      ],
      $this->symbols["TURTLE"] => [
        "left" => "32",
        "top" => "27",
        "rotation" => "-20",
        "size" => "40",
      ],
    ],
  ],
  '33' => [
    'type' => '0002041828293856',
    'zones' => [
      $this->symbols["CHEESE"] => [
        "left" => "6",
        "top" => "14",
        "rotation" => "42",
        "size" => "32",
      ],
      $this->symbols["CLOVER"] => [
        "left" => "6",
        "top" => "41",
        "rotation" => "128",
        "size" => "35",
      ],
      $this->symbols["EXCLAMATION"] => [
        "left" => "33",
        "top" => "5",
        "rotation" => "-47",
        "size" => "32",
      ],
      $this->symbols["ICECUBE"] => [
        "left" => "29",
        "top" => "70",
        "rotation" => "185",
        "size" => "26",
      ],
      $this->symbols["PENCIL"] => [
        "left" => "56",
        "top" => "12",
        "rotation" => "0",
        "size" => "31",
      ],
      $this->symbols["TARGET"] => [
        "left" => "74",
        "top" => "37",
        "rotation" => "222",
        "size" => "21",
      ],
      $this->symbols["TREE"] => [
        "left" => "51",
        "top" => "52",
        "rotation" => "5",
        "size" => "36",
      ],
      $this->symbols["TURTLE"] => [
        "left" => "32",
        "top" => "27",
        "rotation" => "-20",
        "size" => "40",
      ],
    ],
  ],
  '34' => [
    'type' => '0809202129344654',
    'zones' => [
      $this->symbols["CHEESE"] => [
        "left" => "6",
        "top" => "14",
        "rotation" => "42",
        "size" => "32",
      ],
      $this->symbols["CLOVER"] => [
        "left" => "6",
        "top" => "41",
        "rotation" => "128",
        "size" => "35",
      ],
      $this->symbols["EXCLAMATION"] => [
        "left" => "33",
        "top" => "5",
        "rotation" => "-47",
        "size" => "32",
      ],
      $this->symbols["ICECUBE"] => [
        "left" => "29",
        "top" => "70",
        "rotation" => "185",
        "size" => "26",
      ],
      $this->symbols["PENCIL"] => [
        "left" => "56",
        "top" => "12",
        "rotation" => "0",
        "size" => "31",
      ],
      $this->symbols["TARGET"] => [
        "left" => "74",
        "top" => "37",
        "rotation" => "222",
        "size" => "21",
      ],
      $this->symbols["TREE"] => [
        "left" => "51",
        "top" => "52",
        "rotation" => "5",
        "size" => "36",
      ],
      $this->symbols["TURTLE"] => [
        "left" => "32",
        "top" => "27",
        "rotation" => "-20",
        "size" => "40",
      ],
    ],
  ],
  '35' => [
    'type' => '0001031619263453',
    'zones' => [
      $this->symbols["CHEESE"] => [
        "left" => "6",
        "top" => "14",
        "rotation" => "42",
        "size" => "32",
      ],
      $this->symbols["CLOVER"] => [
        "left" => "6",
        "top" => "41",
        "rotation" => "128",
        "size" => "35",
      ],
      $this->symbols["EXCLAMATION"] => [
        "left" => "33",
        "top" => "5",
        "rotation" => "-47",
        "size" => "32",
      ],
      $this->symbols["ICECUBE"] => [
        "left" => "29",
        "top" => "70",
        "rotation" => "185",
        "size" => "26",
      ],
      $this->symbols["PENCIL"] => [
        "left" => "56",
        "top" => "12",
        "rotation" => "0",
        "size" => "31",
      ],
      $this->symbols["TARGET"] => [
        "left" => "74",
        "top" => "37",
        "rotation" => "222",
        "size" => "21",
      ],
      $this->symbols["TREE"] => [
        "left" => "51",
        "top" => "52",
        "rotation" => "5",
        "size" => "36",
      ],
      $this->symbols["TURTLE"] => [
        "left" => "32",
        "top" => "27",
        "rotation" => "-20",
        "size" => "40",
      ],
    ],
  ],
  '36' => [
    'type' => '0005060720424852',
    'zones' => [
      $this->symbols["CHEESE"] => [
        "left" => "6",
        "top" => "14",
        "rotation" => "42",
        "size" => "32",
      ],
      $this->symbols["CLOVER"] => [
        "left" => "6",
        "top" => "41",
        "rotation" => "128",
        "size" => "35",
      ],
      $this->symbols["EXCLAMATION"] => [
        "left" => "33",
        "top" => "5",
        "rotation" => "-47",
        "size" => "32",
      ],
      $this->symbols["ICECUBE"] => [
        "left" => "29",
        "top" => "70",
        "rotation" => "185",
        "size" => "26",
      ],
      $this->symbols["PENCIL"] => [
        "left" => "56",
        "top" => "12",
        "rotation" => "0",
        "size" => "31",
      ],
      $this->symbols["TARGET"] => [
        "left" => "74",
        "top" => "37",
        "rotation" => "222",
        "size" => "21",
      ],
      $this->symbols["TREE"] => [
        "left" => "51",
        "top" => "52",
        "rotation" => "5",
        "size" => "36",
      ],
      $this->symbols["TURTLE"] => [
        "left" => "32",
        "top" => "27",
        "rotation" => "-20",
        "size" => "40",
      ],
    ],
  ],
  '37' => [
    'type' => '1820303235364053',
    'zones' => [
      $this->symbols["CHEESE"] => [
        "left" => "6",
        "top" => "14",
        "rotation" => "42",
        "size" => "32",
      ],
      $this->symbols["CLOVER"] => [
        "left" => "6",
        "top" => "41",
        "rotation" => "128",
        "size" => "35",
      ],
      $this->symbols["EXCLAMATION"] => [
        "left" => "33",
        "top" => "5",
        "rotation" => "-47",
        "size" => "32",
      ],
      $this->symbols["ICECUBE"] => [
        "left" => "29",
        "top" => "70",
        "rotation" => "185",
        "size" => "26",
      ],
      $this->symbols["PENCIL"] => [
        "left" => "56",
        "top" => "12",
        "rotation" => "0",
        "size" => "31",
      ],
      $this->symbols["TARGET"] => [
        "left" => "74",
        "top" => "37",
        "rotation" => "222",
        "size" => "21",
      ],
      $this->symbols["TREE"] => [
        "left" => "51",
        "top" => "52",
        "rotation" => "5",
        "size" => "36",
      ],
      $this->symbols["TURTLE"] => [
        "left" => "32",
        "top" => "27",
        "rotation" => "-20",
        "size" => "40",
      ],
    ],
  ],
  '38' => [
    'type' => '0407212537394353',
    'zones' => [
      $this->symbols["CHEESE"] => [
        "left" => "6",
        "top" => "14",
        "rotation" => "42",
        "size" => "32",
      ],
      $this->symbols["CLOVER"] => [
        "left" => "6",
        "top" => "41",
        "rotation" => "128",
        "size" => "35",
      ],
      $this->symbols["EXCLAMATION"] => [
        "left" => "33",
        "top" => "5",
        "rotation" => "-47",
        "size" => "32",
      ],
      $this->symbols["ICECUBE"] => [
        "left" => "29",
        "top" => "70",
        "rotation" => "185",
        "size" => "26",
      ],
      $this->symbols["PENCIL"] => [
        "left" => "56",
        "top" => "12",
        "rotation" => "0",
        "size" => "31",
      ],
      $this->symbols["TARGET"] => [
        "left" => "74",
        "top" => "37",
        "rotation" => "222",
        "size" => "21",
      ],
      $this->symbols["TREE"] => [
        "left" => "51",
        "top" => "52",
        "rotation" => "5",
        "size" => "36",
      ],
      $this->symbols["TURTLE"] => [
        "left" => "32",
        "top" => "27",
        "rotation" => "-20",
        "size" => "40",
      ],
    ],
  ],
  '39' => [
    'type' => '0711262729333544',
    'zones' => [
      $this->symbols["CHEESE"] => [
        "left" => "6",
        "top" => "14",
        "rotation" => "42",
        "size" => "32",
      ],
      $this->symbols["CLOVER"] => [
        "left" => "6",
        "top" => "41",
        "rotation" => "128",
        "size" => "35",
      ],
      $this->symbols["EXCLAMATION"] => [
        "left" => "33",
        "top" => "5",
        "rotation" => "-47",
        "size" => "32",
      ],
      $this->symbols["ICECUBE"] => [
        "left" => "29",
        "top" => "70",
        "rotation" => "185",
        "size" => "26",
      ],
      $this->symbols["PENCIL"] => [
        "left" => "56",
        "top" => "12",
        "rotation" => "0",
        "size" => "31",
      ],
      $this->symbols["TARGET"] => [
        "left" => "74",
        "top" => "37",
        "rotation" => "222",
        "size" => "21",
      ],
      $this->symbols["TREE"] => [
        "left" => "51",
        "top" => "52",
        "rotation" => "5",
        "size" => "36",
      ],
      $this->symbols["TURTLE"] => [
        "left" => "32",
        "top" => "27",
        "rotation" => "-20",
        "size" => "40",
      ],
    ],
  ],
  '40' => [
    'type' => '3435374751525556',
    'zones' => [
      $this->symbols["CHEESE"] => [
        "left" => "6",
        "top" => "14",
        "rotation" => "42",
        "size" => "32",
      ],
      $this->symbols["CLOVER"] => [
        "left" => "6",
        "top" => "41",
        "rotation" => "128",
        "size" => "35",
      ],
      $this->symbols["EXCLAMATION"] => [
        "left" => "33",
        "top" => "5",
        "rotation" => "-47",
        "size" => "32",
      ],
      $this->symbols["ICECUBE"] => [
        "left" => "29",
        "top" => "70",
        "rotation" => "185",
        "size" => "26",
      ],
      $this->symbols["PENCIL"] => [
        "left" => "56",
        "top" => "12",
        "rotation" => "0",
        "size" => "31",
      ],
      $this->symbols["TARGET"] => [
        "left" => "74",
        "top" => "37",
        "rotation" => "222",
        "size" => "21",
      ],
      $this->symbols["TREE"] => [
        "left" => "51",
        "top" => "52",
        "rotation" => "5",
        "size" => "36",
      ],
      $this->symbols["TURTLE"] => [
        "left" => "32",
        "top" => "27",
        "rotation" => "-20",
        "size" => "40",
      ],
    ],
  ],
  '41' => [
    'type' => '0010121327323754',
    'zones' => [
      $this->symbols["CHEESE"] => [
        "left" => "6",
        "top" => "14",
        "rotation" => "42",
        "size" => "32",
      ],
      $this->symbols["CLOVER"] => [
        "left" => "6",
        "top" => "41",
        "rotation" => "128",
        "size" => "35",
      ],
      $this->symbols["EXCLAMATION"] => [
        "left" => "33",
        "top" => "5",
        "rotation" => "-47",
        "size" => "32",
      ],
      $this->symbols["ICECUBE"] => [
        "left" => "29",
        "top" => "70",
        "rotation" => "185",
        "size" => "26",
      ],
      $this->symbols["PENCIL"] => [
        "left" => "56",
        "top" => "12",
        "rotation" => "0",
        "size" => "31",
      ],
      $this->symbols["TARGET"] => [
        "left" => "74",
        "top" => "37",
        "rotation" => "222",
        "size" => "21",
      ],
      $this->symbols["TREE"] => [
        "left" => "51",
        "top" => "52",
        "rotation" => "5",
        "size" => "36",
      ],
      $this->symbols["TURTLE"] => [
        "left" => "32",
        "top" => "27",
        "rotation" => "-20",
        "size" => "40",
      ],
    ],
  ],
  '42' => [
    'type' => '0102142024252755',
    'zones' => [
      $this->symbols["CHEESE"] => [
        "left" => "6",
        "top" => "14",
        "rotation" => "42",
        "size" => "32",
      ],
      $this->symbols["CLOVER"] => [
        "left" => "6",
        "top" => "41",
        "rotation" => "128",
        "size" => "35",
      ],
      $this->symbols["EXCLAMATION"] => [
        "left" => "33",
        "top" => "5",
        "rotation" => "-47",
        "size" => "32",
      ],
      $this->symbols["ICECUBE"] => [
        "left" => "29",
        "top" => "70",
        "rotation" => "185",
        "size" => "26",
      ],
      $this->symbols["PENCIL"] => [
        "left" => "56",
        "top" => "12",
        "rotation" => "0",
        "size" => "31",
      ],
      $this->symbols["TARGET"] => [
        "left" => "74",
        "top" => "37",
        "rotation" => "222",
        "size" => "21",
      ],
      $this->symbols["TREE"] => [
        "left" => "51",
        "top" => "52",
        "rotation" => "5",
        "size" => "36",
      ],
      $this->symbols["TURTLE"] => [
        "left" => "32",
        "top" => "27",
        "rotation" => "-20",
        "size" => "40",
      ],
    ],
  ],
  '43' => [
    'type' => '0810333845485355',
    'zones' => [
      $this->symbols["CHEESE"] => [
        "left" => "6",
        "top" => "14",
        "rotation" => "42",
        "size" => "32",
      ],
      $this->symbols["CLOVER"] => [
        "left" => "6",
        "top" => "41",
        "rotation" => "128",
        "size" => "35",
      ],
      $this->symbols["EXCLAMATION"] => [
        "left" => "33",
        "top" => "5",
        "rotation" => "-47",
        "size" => "32",
      ],
      $this->symbols["ICECUBE"] => [
        "left" => "29",
        "top" => "70",
        "rotation" => "185",
        "size" => "26",
      ],
      $this->symbols["PENCIL"] => [
        "left" => "56",
        "top" => "12",
        "rotation" => "0",
        "size" => "31",
      ],
      $this->symbols["TARGET"] => [
        "left" => "74",
        "top" => "37",
        "rotation" => "222",
        "size" => "21",
      ],
      $this->symbols["TREE"] => [
        "left" => "51",
        "top" => "52",
        "rotation" => "5",
        "size" => "36",
      ],
      $this->symbols["TURTLE"] => [
        "left" => "32",
        "top" => "27",
        "rotation" => "-20",
        "size" => "40",
      ],
    ],
  ],
  '44' => [
    'type' => '0710141623404656',
    'zones' => [
      $this->symbols["CHEESE"] => [
        "left" => "6",
        "top" => "14",
        "rotation" => "42",
        "size" => "32",
      ],
      $this->symbols["CLOVER"] => [
        "left" => "6",
        "top" => "41",
        "rotation" => "128",
        "size" => "35",
      ],
      $this->symbols["EXCLAMATION"] => [
        "left" => "33",
        "top" => "5",
        "rotation" => "-47",
        "size" => "32",
      ],
      $this->symbols["ICECUBE"] => [
        "left" => "29",
        "top" => "70",
        "rotation" => "185",
        "size" => "26",
      ],
      $this->symbols["PENCIL"] => [
        "left" => "56",
        "top" => "12",
        "rotation" => "0",
        "size" => "31",
      ],
      $this->symbols["TARGET"] => [
        "left" => "74",
        "top" => "37",
        "rotation" => "222",
        "size" => "21",
      ],
      $this->symbols["TREE"] => [
        "left" => "51",
        "top" => "52",
        "rotation" => "5",
        "size" => "36",
      ],
      $this->symbols["TURTLE"] => [
        "left" => "32",
        "top" => "27",
        "rotation" => "-20",
        "size" => "40",
      ],
    ],
  ],
  '45' => [
    'type' => '0514193135383954',
    'zones' => [
      $this->symbols["CHEESE"] => [
        "left" => "6",
        "top" => "14",
        "rotation" => "42",
        "size" => "32",
      ],
      $this->symbols["CLOVER"] => [
        "left" => "6",
        "top" => "41",
        "rotation" => "128",
        "size" => "35",
      ],
      $this->symbols["EXCLAMATION"] => [
        "left" => "33",
        "top" => "5",
        "rotation" => "-47",
        "size" => "32",
      ],
      $this->symbols["ICECUBE"] => [
        "left" => "29",
        "top" => "70",
        "rotation" => "185",
        "size" => "26",
      ],
      $this->symbols["PENCIL"] => [
        "left" => "56",
        "top" => "12",
        "rotation" => "0",
        "size" => "31",
      ],
      $this->symbols["TARGET"] => [
        "left" => "74",
        "top" => "37",
        "rotation" => "222",
        "size" => "21",
      ],
      $this->symbols["TREE"] => [
        "left" => "51",
        "top" => "52",
        "rotation" => "5",
        "size" => "36",
      ],
      $this->symbols["TURTLE"] => [
        "left" => "32",
        "top" => "27",
        "rotation" => "-20",
        "size" => "40",
      ],
    ],
  ],
  '46' => [
    'type' => '0122303738424446',
    'zones' => [
      $this->symbols["CHEESE"] => [
        "left" => "6",
        "top" => "14",
        "rotation" => "42",
        "size" => "32",
      ],
      $this->symbols["CLOVER"] => [
        "left" => "6",
        "top" => "41",
        "rotation" => "128",
        "size" => "35",
      ],
      $this->symbols["EXCLAMATION"] => [
        "left" => "33",
        "top" => "5",
        "rotation" => "-47",
        "size" => "32",
      ],
      $this->symbols["ICECUBE"] => [
        "left" => "29",
        "top" => "70",
        "rotation" => "185",
        "size" => "26",
      ],
      $this->symbols["PENCIL"] => [
        "left" => "56",
        "top" => "12",
        "rotation" => "0",
        "size" => "31",
      ],
      $this->symbols["TARGET"] => [
        "left" => "74",
        "top" => "37",
        "rotation" => "222",
        "size" => "21",
      ],
      $this->symbols["TREE"] => [
        "left" => "51",
        "top" => "52",
        "rotation" => "5",
        "size" => "36",
      ],
      $this->symbols["TURTLE"] => [
        "left" => "32",
        "top" => "27",
        "rotation" => "-20",
        "size" => "40",
      ],
    ],
  ],
  '47' => [
    'type' => '0419273641464851',
    'zones' => [
      $this->symbols["CHEESE"] => [
        "left" => "6",
        "top" => "14",
        "rotation" => "42",
        "size" => "32",
      ],
      $this->symbols["CLOVER"] => [
        "left" => "6",
        "top" => "41",
        "rotation" => "128",
        "size" => "35",
      ],
      $this->symbols["EXCLAMATION"] => [
        "left" => "33",
        "top" => "5",
        "rotation" => "-47",
        "size" => "32",
      ],
      $this->symbols["ICECUBE"] => [
        "left" => "29",
        "top" => "70",
        "rotation" => "185",
        "size" => "26",
      ],
      $this->symbols["PENCIL"] => [
        "left" => "56",
        "top" => "12",
        "rotation" => "0",
        "size" => "31",
      ],
      $this->symbols["TARGET"] => [
        "left" => "74",
        "top" => "37",
        "rotation" => "222",
        "size" => "21",
      ],
      $this->symbols["TREE"] => [
        "left" => "51",
        "top" => "52",
        "rotation" => "5",
        "size" => "36",
      ],
      $this->symbols["TURTLE"] => [
        "left" => "32",
        "top" => "27",
        "rotation" => "-20",
        "size" => "40",
      ],
    ],
  ],
  '48' => [
    'type' => '1315192940424355',
    'zones' => [
      $this->symbols["CHEESE"] => [
        "left" => "6",
        "top" => "14",
        "rotation" => "42",
        "size" => "32",
      ],
      $this->symbols["CLOVER"] => [
        "left" => "6",
        "top" => "41",
        "rotation" => "128",
        "size" => "35",
      ],
      $this->symbols["EXCLAMATION"] => [
        "left" => "33",
        "top" => "5",
        "rotation" => "-47",
        "size" => "32",
      ],
      $this->symbols["ICECUBE"] => [
        "left" => "29",
        "top" => "70",
        "rotation" => "185",
        "size" => "26",
      ],
      $this->symbols["PENCIL"] => [
        "left" => "56",
        "top" => "12",
        "rotation" => "0",
        "size" => "31",
      ],
      $this->symbols["TARGET"] => [
        "left" => "74",
        "top" => "37",
        "rotation" => "222",
        "size" => "21",
      ],
      $this->symbols["TREE"] => [
        "left" => "51",
        "top" => "52",
        "rotation" => "5",
        "size" => "36",
      ],
      $this->symbols["TURTLE"] => [
        "left" => "32",
        "top" => "27",
        "rotation" => "-20",
        "size" => "40",
      ],
    ],
  ],
  '49' => [
    'type' => '0210113436394250',
    'zones' => [
      $this->symbols["CHEESE"] => [
        "left" => "6",
        "top" => "14",
        "rotation" => "42",
        "size" => "32",
      ],
      $this->symbols["CLOVER"] => [
        "left" => "6",
        "top" => "41",
        "rotation" => "128",
        "size" => "35",
      ],
      $this->symbols["EXCLAMATION"] => [
        "left" => "33",
        "top" => "5",
        "rotation" => "-47",
        "size" => "32",
      ],
      $this->symbols["ICECUBE"] => [
        "left" => "29",
        "top" => "70",
        "rotation" => "185",
        "size" => "26",
      ],
      $this->symbols["PENCIL"] => [
        "left" => "56",
        "top" => "12",
        "rotation" => "0",
        "size" => "31",
      ],
      $this->symbols["TARGET"] => [
        "left" => "74",
        "top" => "37",
        "rotation" => "222",
        "size" => "21",
      ],
      $this->symbols["TREE"] => [
        "left" => "51",
        "top" => "52",
        "rotation" => "5",
        "size" => "36",
      ],
      $this->symbols["TURTLE"] => [
        "left" => "32",
        "top" => "27",
        "rotation" => "-20",
        "size" => "40",
      ],
    ],
  ],
  '50' => [
    'type' => '0008141736434447',
    'zones' => [
      $this->symbols["CHEESE"] => [
        "left" => "6",
        "top" => "14",
        "rotation" => "42",
        "size" => "32",
      ],
      $this->symbols["CLOVER"] => [
        "left" => "6",
        "top" => "41",
        "rotation" => "128",
        "size" => "35",
      ],
      $this->symbols["EXCLAMATION"] => [
        "left" => "33",
        "top" => "5",
        "rotation" => "-47",
        "size" => "32",
      ],
      $this->symbols["ICECUBE"] => [
        "left" => "29",
        "top" => "70",
        "rotation" => "185",
        "size" => "26",
      ],
      $this->symbols["PENCIL"] => [
        "left" => "56",
        "top" => "12",
        "rotation" => "0",
        "size" => "31",
      ],
      $this->symbols["TARGET"] => [
        "left" => "74",
        "top" => "37",
        "rotation" => "222",
        "size" => "21",
      ],
      $this->symbols["TREE"] => [
        "left" => "51",
        "top" => "52",
        "rotation" => "5",
        "size" => "36",
      ],
      $this->symbols["TURTLE"] => [
        "left" => "32",
        "top" => "27",
        "rotation" => "-20",
        "size" => "40",
      ],
    ],
  ],
  '51' => [
    'type' => '1112162038434951',
    'zones' => [
      $this->symbols["CHEESE"] => [
        "left" => "6",
        "top" => "14",
        "rotation" => "42",
        "size" => "32",
      ],
      $this->symbols["CLOVER"] => [
        "left" => "6",
        "top" => "41",
        "rotation" => "128",
        "size" => "35",
      ],
      $this->symbols["EXCLAMATION"] => [
        "left" => "33",
        "top" => "5",
        "rotation" => "-47",
        "size" => "32",
      ],
      $this->symbols["ICECUBE"] => [
        "left" => "29",
        "top" => "70",
        "rotation" => "185",
        "size" => "26",
      ],
      $this->symbols["PENCIL"] => [
        "left" => "56",
        "top" => "12",
        "rotation" => "0",
        "size" => "31",
      ],
      $this->symbols["TARGET"] => [
        "left" => "74",
        "top" => "37",
        "rotation" => "222",
        "size" => "21",
      ],
      $this->symbols["TREE"] => [
        "left" => "51",
        "top" => "52",
        "rotation" => "5",
        "size" => "36",
      ],
      $this->symbols["TURTLE"] => [
        "left" => "32",
        "top" => "27",
        "rotation" => "-20",
        "size" => "40",
      ],
    ],
  ],
  '52' => [
    'type' => '0511132428464753',
    'zones' => [
      $this->symbols["CHEESE"] => [
        "left" => "6",
        "top" => "14",
        "rotation" => "42",
        "size" => "32",
      ],
      $this->symbols["CLOVER"] => [
        "left" => "6",
        "top" => "41",
        "rotation" => "128",
        "size" => "35",
      ],
      $this->symbols["EXCLAMATION"] => [
        "left" => "33",
        "top" => "5",
        "rotation" => "-47",
        "size" => "32",
      ],
      $this->symbols["ICECUBE"] => [
        "left" => "29",
        "top" => "70",
        "rotation" => "185",
        "size" => "26",
      ],
      $this->symbols["PENCIL"] => [
        "left" => "56",
        "top" => "12",
        "rotation" => "0",
        "size" => "31",
      ],
      $this->symbols["TARGET"] => [
        "left" => "74",
        "top" => "37",
        "rotation" => "222",
        "size" => "21",
      ],
      $this->symbols["TREE"] => [
        "left" => "51",
        "top" => "52",
        "rotation" => "5",
        "size" => "36",
      ],
      $this->symbols["TURTLE"] => [
        "left" => "32",
        "top" => "27",
        "rotation" => "-20",
        "size" => "40",
      ],
    ],
  ],
  '53' => [
    'type' => '0207091219304547',
    'zones' => [
      $this->symbols["CHEESE"] => [
        "left" => "6",
        "top" => "14",
        "rotation" => "42",
        "size" => "32",
      ],
      $this->symbols["CLOVER"] => [
        "left" => "6",
        "top" => "41",
        "rotation" => "128",
        "size" => "35",
      ],
      $this->symbols["EXCLAMATION"] => [
        "left" => "33",
        "top" => "5",
        "rotation" => "-47",
        "size" => "32",
      ],
      $this->symbols["ICECUBE"] => [
        "left" => "29",
        "top" => "70",
        "rotation" => "185",
        "size" => "26",
      ],
      $this->symbols["PENCIL"] => [
        "left" => "56",
        "top" => "12",
        "rotation" => "0",
        "size" => "31",
      ],
      $this->symbols["TARGET"] => [
        "left" => "74",
        "top" => "37",
        "rotation" => "222",
        "size" => "21",
      ],
      $this->symbols["TREE"] => [
        "left" => "51",
        "top" => "52",
        "rotation" => "5",
        "size" => "36",
      ],
      $this->symbols["TURTLE"] => [
        "left" => "32",
        "top" => "27",
        "rotation" => "-20",
        "size" => "40",
      ],
    ],
  ],
  '54' => [
    'type' => '0304081223243542',
    'zones' => [
      $this->symbols["CHEESE"] => [
        "left" => "6",
        "top" => "14",
        "rotation" => "42",
        "size" => "32",
      ],
      $this->symbols["CLOVER"] => [
        "left" => "6",
        "top" => "41",
        "rotation" => "128",
        "size" => "35",
      ],
      $this->symbols["EXCLAMATION"] => [
        "left" => "33",
        "top" => "5",
        "rotation" => "-47",
        "size" => "32",
      ],
      $this->symbols["ICECUBE"] => [
        "left" => "29",
        "top" => "70",
        "rotation" => "185",
        "size" => "26",
      ],
      $this->symbols["PENCIL"] => [
        "left" => "56",
        "top" => "12",
        "rotation" => "0",
        "size" => "31",
      ],
      $this->symbols["TARGET"] => [
        "left" => "74",
        "top" => "37",
        "rotation" => "222",
        "size" => "21",
      ],
      $this->symbols["TREE"] => [
        "left" => "51",
        "top" => "52",
        "rotation" => "5",
        "size" => "36",
      ],
      $this->symbols["TURTLE"] => [
        "left" => "32",
        "top" => "27",
        "rotation" => "-20",
        "size" => "40",
      ],
    ],
  ],

);
